POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "spoon",
  "price": 10,
  "image_url": "imgfork",
  "description": "a spoon texttext",
  "inventory": "1"
}

###

DELETE http://localhost:3000/products/7.json


###

PATCH http://localhost:3000/products/11.json
Content-Type: application/json

{
  "image_url": "imgspoon"
}